### ISSUE TITLE
Cross platform CLT

### ISSUE THREAD

**Issue by setanarut** [TadaTeruki/fastlem#1]
I'm writing here because the Discussion feature is turned off. [These greycale height maps](https://github.com/TadaTeruki/fastlem/blob/main/images/out/landscape_evolution.png) are perfect for [fractal GIF animations](https://github.com/setanarut/halftonism). The even thickness of the branches makes them suitable for halftone. I need it. but I don't understand Rust language and I don't want to install the Rust environment. Do you plan to release a cross-platform command line tool? Thanks.

https://billtavis.com/blogs/halftonism-is-the-new-cubism/the-making-of-trying-to-hold-it-together-cnc-halftone
https://github.com/setanarut/halftonism

**Comment by TadaTeruki** [comment]
Thank you for your suggestion.

> I'm writing here because the Discussion feature is turned off.

That was my configuration mistake, so I have now turned on the discussion feature. However, I will continue this discussion on this issue.

> Do you plan to release a cross-platform command line tool?

This project was created as a pure Rust library, abstracting only the simulation part, and I had not thought of using it in this way. However, I think it is a very interesting suggestion.

I would like to know what kind of usage (commands and options) you are thinking of as a command line tool, even if it is abstract.

There have been some comments on reddit (although the post has since been removed) about the lack of a command line tool, so this may be a subproject of fastlem to take forward.

**Comment by setanarut** [comment]
> I would like to know what kind of usage (commands and options) you are thinking of as a command line tool, even if it is abstract.

A command to save a high-resolution greyscale height map image would be nice. 

### For example:

```Zsh
brew install fastlem
```

```Zsh
fastlem --size 5000x5000 --randomseed 1923 -o ~/Desktop/myHeightMap.png
```

There may also be some cool parameters that I don't understand.

**Comment by TadaTeruki** [comment]
Thank you. I'm creating this.

https://github.com/TadaTeruki/fastlem-random-terrain

I want to keep fastlem as a library only for simulation, so I implemented it as a separate project.

You can already try this if you have cargo or docker in your development environment. The documentation is not yet sufficient, and some command options are different from your request (and can be changed), but this will be useful.

If you think this is acceptable, I would like to continue this discussion to separate issues (or `discussion' if you need it) of the repository.

**Comment by TadaTeruki** [comment]
P.S. There are still many mistakes (for example: --image-file should be renamed to another name such as --output)

**Comment by setanarut** [comment]
Thanks. I tried but. I don't need the sea. I couldn't find a way to produce it without sea. How can I do this without a slope or a sea?

Like this:
https://github.com/TadaTeruki/fastlem/blob/main/images/out/landscape_evolution.png

**Comment by setanarut** [comment]
I'm talking about the black areas (sea)

```
./fastlem-random-terrain -p 100000 -s 23 -e 20 -b 100:100 -i 1000:1000
```

![terrain](https://github.com/TadaTeruki/fastlem/assets/36481442/176576f1-062f-4ffd-b1dc-02f6557f3b44)
